Repository fylein/fyle-platform-docs, pull requests merged in 2024-10, with the labels that each got.

#549 feat: Add `POST admin/corporate_card_transactions/assign/bulk` API Docs
  reference/admin.yaml
  src/admin/openapi.yaml
  src/admin/paths/admin@corporate_card_transactions@assign@bulk.yaml
Labels: size/M

#550 feat: Docs for `POST admin/corporate_card_transactions/reassign/bulk`
  reference/admin.yaml
  src/admin/openapi.yaml
  src/admin/paths/admin@corporate_card_transactions@reassign@bulk.yaml
  src/components/schemas/corporate_card_transaction.yaml
Labels: size/M

#555 feat: Docs for `POST admin/corporate_card_transactions/ignore/bulk`
  reference/admin.yaml
  src/admin/openapi.yaml
Labels: size/M

#554 feat: POST /<admin/approver>/expenses/bulk
  reference/admin.yaml
  reference/approver.yaml
  src/admin/openapi.yaml
  src/admin/paths/admin@expenses@bulk.yaml
  src/approver/openapi.yaml
  src/approver/paths/approver@expenses@bulk.yaml
  src/components/schemas/expense.yaml
Labels: size/L

#552 feat: Additional fields POST /<role>/expenses
  reference/admin.yaml
  reference/approver.yaml
  reference/spender.yaml
  src/components/schemas/expense.yaml
  src/components/schemas/fields.yaml
Labels: size/L

#558 feat: added statement_card_number input in /preview API
  reference/admin.yaml
  src/admin/paths/admin@statements@preview.yaml
  src/components/schemas/statements.yaml
Labels: size/M

#560 feat: Added card_mapping key in /missing_transactions API
  reference/admin.yaml
  src/components/schemas/statements.yaml
Labels: size/XS

#564 feat: Added c1_virtual_card_last_four
  reference/admin.yaml
  reference/spender.yaml
  src/components/schemas/corporate_card_transaction.yaml
Labels: size/M

#561 feat: Added docs for `GET /approver/cost_centers`
  reference/approver.yaml
  src/approver/openapi.yaml
  src/approver/paths/approver@cost_centers.yaml
  src/components/schemas/cost_center.yaml
Labels: size/M

#566 feat: Added user key in /matching_cards API
  reference/admin.yaml
  src/components/schemas/statements.yaml
Labels: size/XS

#562 feat: Added doc for `GET /approver/per_diem_rates`
  reference/approver.yaml
  src/approver/openapi.yaml
  src/approver/paths/approver@per_diem_rates.yaml
Labels: size/S

#565 feat: Added doc for `GET /approver/mileage_rates`
  reference/approver.yaml
  src/approver/openapi.yaml
  src/approver/paths/approver@mileage_rates.yaml
Labels: size/S

#567 feat: Added c1_virtual_card_last_four to expense_out
  reference/admin.yaml
  reference/approver.yaml
  reference/spender.yaml
  src/components/schemas/expense.yaml
Labels: size/S

#569 fix: remove Github access token used in github actions
  .github/workflows/bundler.yml
Labels: size/XS

#568 feat: Add support for account_type field in get personal cards
  reference/spender.yaml
  src/components/schemas/personal_card.yaml
Labels: size/XS
