Repository fylein/fyle-platform-docs, pull requests merged in 2024-12, with the labels that each got.

#576 feat: add sub_feature column in report filters
  reference/admin.yaml
  reference/approver.yaml
  reference/spender.yaml
  src/components/schemas/report_filters.yaml
Labels: size/XS

#570 feat: post approver/admin per_diem expenses
  reference/admin.yaml
  reference/approver.yaml
  src/components/schemas/expense.yaml
Labels: size/M

#578 fix: Revert "feat: post approver/admin per_diem expenses"
  reference/admin.yaml
  reference/approver.yaml
  src/components/schemas/expense.yaml
Labels: size/M

#577 feat: support fractional values for per_deim_num_days
  reference/admin.yaml
  reference/approver.yaml
  reference/spender.yaml
  src/components/schemas/expense.yaml
Labels: size/S

#585 feat: Revert approver file ids
  reference/approver.yaml
  src/components/schemas/expense.yaml
Labels: size/L

#584 feat: revert 554 POST /<admin/approver>/expenses/bulk
  reference/admin.yaml
  reference/approver.yaml
  src/admin/openapi.yaml
  src/admin/paths/admin@expenses@bulk.yaml
  src/approver/openapi.yaml
  src/approver/paths/approver@expenses@bulk.yaml
  src/components/schemas/expense.yaml
Labels: size/L

#580 feat: Add group_by_state support to expenses stats API
  reference/admin.yaml
  reference/approver.yaml
  reference/spender.yaml
  src/components/schemas/expense.yaml
Labels: size/L

#582 feat: Add group_by_state support to advance request stats API
  reference/admin.yaml
  reference/spender.yaml
  src/components/schemas/advance_request.yaml
Labels: size/L

#586 feat: Add group_by_state support to reports stats API
  reference/admin.yaml
  reference/approver.yaml
  reference/spender.yaml
  src/components/schemas/report.yaml
Labels: size/XL

#587 feat: Add group-by-state support to stats APIs for expenses, advance_requests, and reports
  reference/admin.yaml
  reference/approver.yaml
  reference/spender.yaml
  src/components/schemas/advance_request.yaml
  src/components/schemas/expense.yaml
  src/components/schemas/report.yaml
Labels: size/XL

#589 feat: Allow mileage calculated fields in POST /<roles/expenses>
  reference/admin.yaml
  reference/approver.yaml
  reference/spender.yaml
  src/components/schemas/expense.yaml
Labels: size/XL
