Repository fylein/fyle-platform-docs, pull requests merged in 2025-03, with the labels that each got.

#594 fix: Remove dead actions and add new supported actions for admin subscriptions
  reference/admin.yaml
  reference/approver.yaml
  reference/spender.yaml
  src/admin/paths/admin@subscriptions.yaml
  src/approver/paths/approver@subscriptions.yaml
  src/components/schemas/report.yaml
  src/spender/paths/spender@subscriptions.yaml
Labels: size/M

#609 feat: added approver employees list api
  reference/approver.yaml
  src/approver/openapi.yaml
  src/approver/paths/approver@employees.yaml
Labels: size/XL

#611 feat: Add API docs for `POST <role>/expenses/permissions` API
  reference/admin.yaml
  reference/approver.yaml
  reference/spender.yaml
  src/admin/openapi.yaml
  src/admin/paths/admin@expenses@permissions.yaml
  src/approver/openapi.yaml
  src/approver/paths/approver@expenses@permissions.yaml
  src/components/schemas/expense.yaml
  src/spender/openapi.yaml
  src/spender/paths/spender@expenses@permissions.yaml
Labels: size/L

#612 feat: Add corporate card id to spender cct and expenses stats api doc
  reference/spender.yaml
  src/components/schemas/corporate_card_transaction.yaml
Labels: size/XS

#613 feat: add approver advance requests api doc
  reference/approver.yaml
  src/approver/openapi.yaml
  src/approver/paths/approver@advance_requests.yaml
Labels: size/M

#615 feat: `POST /admin/expense_policy_rules/reorder` API specs
  reference/admin.yaml
  src/admin/openapi.yaml
  src/admin/paths/admin@expense_policies@reorder.yaml
Labels: size/M

#617 fix: help article domain
  reference/admin.yaml
  reference/approver.yaml
  reference/spender.yaml
  src/components/schemas/corporate_card_transactions_exports.yaml
  src/components/schemas/expenses_exports.yaml
  src/components/schemas/reports_exports.yaml
Labels: size/S

#614 feat: Add approver advance requests stats api docs
  reference/approver.yaml
  src/approver/openapi.yaml
  src/approver/paths/approver@advance_requests@stats.yaml
  src/components/schemas/advance_request.yaml
Labels: size/M

#618 feat: Making state, country, city as nullable fields in commute details
  reference/admin.yaml
  reference/approver.yaml
  reference/spender.yaml
  src/components/schemas/fields.yaml
Labels: size/XS

#606 feat: Added id and display_name to spender merchant list api query parameters list.
  reference/spender.yaml
  src/spender/paths/spender@merchants.yaml
Labels: size/S

#620 feat: Add bank_transaction_number in Transactions API
  reference/admin.yaml
  reference/spender.yaml
  src/components/schemas/corporate_card_transaction.yaml
Labels: size/M
