Repository fylein/fyle-platform-docs, pull requests merged in 2025-02, with the labels that each got.

#592 feat: API specs for spender/expenses/check_mandatory_fields/bulk
  reference/spender.yaml
  src/components/schemas/expense.yaml
  src/spender/openapi.yaml
  src/spender/paths/spender@expenses@check_mandatory_fields_bulk.yaml
Labels: size/M

#593 Add is_mobile_verified_key
  reference/admin.yaml
  src/components/schemas/employee.yaml
Labels: size/XL

#591 feat: API spec for spender bulk edit expenses API
  reference/spender.yaml
  src/components/schemas/expense.yaml
  src/spender/openapi.yaml
  src/spender/paths/spender@expenses@bulk.yaml
Labels: size/M

#596 fix: invalid openAPI schema for personal_cards objects
  reference/spender.yaml
  src/components/schemas/personal_card.yaml
Labels: size/XS

#597 fix: type fix for `GET /expense_policy_rules` query param `is_approver_policy`
  reference/admin.yaml
  reference/spender.yaml
  src/admin/paths/admin@expense_policies.yaml
  src/spender/paths/spender@expense_policies.yaml
Labels: size/XS

#599 feat: updated specs post adding new fields to `individual desired states`
  reference/admin.yaml
  reference/approver.yaml
  reference/spender.yaml
  src/components/schemas/fields.yaml
Labels: size/M

#603 fix: added `null` to `approver_source` enum values
  reference/admin.yaml
  reference/approver.yaml
  reference/spender.yaml
  src/components/schemas/fields.yaml
Labels: size/XS

#605 feat: deprecate spender/expenses/add_comment API
  reference/spender.yaml
  src/components/schemas/expense.yaml
  src/spender/openapi.yaml
  src/spender/paths/spender@expenses@add_comment.yaml
Labels: size/M

#607 feat: added `source` field to `expense_policy_rules` response
  reference/admin.yaml
  reference/spender.yaml
  src/components/schemas/expense_policies.yaml
Labels: size/XS

#608 feat: add `rank` field to the `reports_rot.approvals` array objects.
  reference/admin.yaml
  reference/approver.yaml
  reference/spender.yaml
  src/components/schemas/report_approval.yaml
Labels: size/S
