Repository fylein/fyle-platform-docs, pull requests merged in 2025-05, with the labels that each got.

#641 Fix:Fyle-86cyt95j7-make spent at optional
  reference/admin.yaml
  reference/spender.yaml
  src/components/schemas/expense.yaml
Labels: size/XS

#637 feat: Add docs for new endpoint to get yodlee corporate cards
  reference/spender.yaml
  src/components/schemas/corporate_card.yaml
  src/spender/openapi.yaml
  src/spender/paths/spender@corporate_cards@yodlee_accounts.yaml
Labels: size/M

#639 feat: POST role/expenses/comments/bulk
  reference/admin.yaml
  reference/approver.yaml
  reference/spender.yaml
  src/admin/openapi.yaml
  src/admin/paths/admin@expenses@comments@bulk.yaml
  src/approver/openapi.yaml
  src/approver/paths/approver@expenses@comments@bulk.yaml
  src/components/schemas/expense.yaml
  src/spender/openapi.yaml
  src/spender/paths/spender@expenses@comments@bulk.yaml
Labels: size/L

#642 feat: POST /employees/exports API
  reference/admin.yaml
  src/admin/openapi.yaml
  src/admin/paths/admin@employees@exports.yaml
  src/components/schemas/employees_exports.yaml
Labels: size/XL

#646 feat: Added new api spender orgs bank details
  reference/admin.yaml
  reference/spender.yaml
  src/components/schemas/org.yaml
  src/spender/openapi.yaml
  src/spender/paths/spender@orgs_bank_details.yaml
Labels: size/M

#645 feat: add /approver/accounts api docs
  reference/approver.yaml
  src/approver/openapi.yaml
  src/approver/paths/approver@accounts.yaml
Labels: size/M

#647 Feat:Add bulk delete endpoint to admin API spec
  reference/admin.yaml
  src/admin/openapi.yaml
  src/admin/paths/admin@expenses@delete@bulk.yaml
Labels: size/M

#651 fix: add accounts to list of approver tags in openapi spec
  reference/approver.yaml
  src/approver/openapi.yaml
Labels: size/XS

#648 fix: Add yodlee_account_id to corporate cards response
  reference/admin.yaml
  reference/spender.yaml
  src/components/schemas/corporate_card.yaml
Labels: size/S

#650 feat: Add api doc for admin expenses merge api
  reference/admin.yaml
  src/admin/openapi.yaml
  src/admin/paths/admin@expenses@merge.yaml
  src/components/schemas/expense.yaml
Labels: size/L
