Repository fylein/fyle-platform-docs, pull requests merged in 2025-07, with the labels that each got.

#679 fix: secondary emails status code
  reference/spender.yaml
  src/components/schemas/409.yaml
  src/spender/paths/spender@secondary_emails.yaml
  src/spender/paths/spender@secondary_emails@check.yaml
Labels: size/S

#678 feat: Added docs for advance request custom fields post api
  reference/admin.yaml
  src/admin/openapi.yaml
  src/admin/paths/admin@advance_requests@custom_fields.yaml
  src/components/schemas/advance_request.yaml
Labels: size/L

#680 feat: Added docs for advance request custom fields get api
  reference/admin.yaml
  reference/approver.yaml
  reference/spender.yaml
  src/admin/paths/admin@advance_requests@custom_fields.yaml
  src/approver/openapi.yaml
  src/approver/paths/approver@advance_requests@custom_fields.yaml
  src/components/schemas/advance_request.yaml
  src/spender/openapi.yaml
  src/spender/paths/spender@advance_requests@custom_fields.yaml
Labels: size/L

#681 feat: Added custom fields flattened field to advance request output schema
  reference/admin.yaml
  reference/approver.yaml
  reference/spender.yaml
  src/components/schemas/advance_request.yaml
Labels: size/M

#682 feat: update API docs for /admin/reminders to show examples of cron format
  reference/admin.yaml
  src/components/schemas/fields.yaml
Labels: size/M

#685 feat: Added api docs for advance request approver generate file urls
  reference/approver.yaml
  src/approver/openapi.yaml
  src/approver/paths/approver@advance_requests@generate_file_urls@bulk.yaml
  src/components/schemas/advance_request.yaml
Labels: size/M
