Repository fylein/fyle-platform-docs, pull requests merged in 2025-04, with the labels that each got.

#622 feat: updated schema for get /admin/orgs api response
  reference/admin.yaml
  src/components/schemas/org.yaml
Labels: size/S

#623 fix: removed new fields from required section in orgs api
  reference/admin.yaml
  src/components/schemas/org.yaml
Labels: size/XS

#624 feat: added schema for new api: GET /spender/orgs
  reference/spender.yaml
  src/components/schemas/org.yaml
  src/spender/openapi.yaml
  src/spender/paths/spender@orgs.yaml
Labels: size/M

#625 feat: Add Docs for Expense Comments `GET` APIs
  reference/admin.yaml
  reference/approver.yaml
  reference/spender.yaml
  src/admin/openapi.yaml
  src/admin/paths/admin@expenses@comments.yaml
  src/approver/openapi.yaml
  src/approver/paths/approver@expenses@comments.yaml
  src/components/parameters/expense_id.yaml
  src/components/schemas/expense.yaml
  src/components/schemas/fields.yaml
  src/spender/openapi.yaml
  src/spender/paths/spender@expenses@comments.yaml
Labels: size/L

#627 feat: Updated response schema of orgs get api
  reference/admin.yaml
  reference/spender.yaml
  src/components/schemas/org.yaml
Labels: size/M

#629 feat: added schema for new api - org bank details
  reference/admin.yaml
  src/admin/openapi.yaml
  src/admin/paths/admin@orgs_bank_details.yaml
  src/components/schemas/org.yaml
Labels: size/M

#628 feat: Add admin employee summaries list api docs
  reference/admin.yaml
  src/admin/openapi.yaml
  src/admin/paths/admin@employees@summaries.yaml
  src/components/schemas/employee.yaml
Labels: size/M

#636 feat: add admin merchants api docs
  reference/admin.yaml
  src/admin/openapi.yaml
  src/admin/paths/admin@merchants.yaml
Labels: size/M

#635 feat: Add API spec for `POST /admin/expenses/verify/bulk` API
  reference/admin.yaml
  src/admin/openapi.yaml
  src/admin/paths/admin@expenses@verify@bulk.yaml
  src/components/schemas/expense.yaml
Labels: size/M

#638 feat: recently used fields api docs
  reference/spender.yaml
  src/components/schemas/recently_used_fields.yaml
  src/spender/openapi.yaml
  src/spender/paths/spender@recently_used_fields.yaml
Labels: size/M

#640 Feat:FYLE-86cwj7byg-added API spec for expense_bulk_delete
  reference/spender.yaml
  src/spender/openapi.yaml
Labels: size/XS
