Repository fylein/fyle-platform-docs, pull requests merged in 2025-06, with the labels that each got.

#653 feat: updated response of advance request out schema
  reference/admin.yaml
  reference/approver.yaml
  reference/spender.yaml
  src/components/schemas/advance_request.yaml
Labels: size/M

#656 feat: added docs for advance request submit api
  reference/spender.yaml
  src/spender/openapi.yaml
  src/spender/paths/spender@advance_requests@submit.yaml
Labels: size/M

#654 feat: Added spender expense merge api doc
  reference/spender.yaml
  src/spender/openapi.yaml
  src/spender/paths/spender@expenses@merge.yaml
Labels: size/M

#658 feat: Schema for new api: advance request bulk attach files
  reference/admin.yaml
  reference/approver.yaml
  reference/spender.yaml
  src/admin/openapi.yaml
  src/admin/paths/admin@advance_requests@bulk_attach_file.yaml
  src/approver/openapi.yaml
  src/approver/paths/approver@advance_requests@bulk_attach_file.yaml
  src/components/schemas/advance_request.yaml
  src/spender/openapi.yaml
  src/spender/paths/spender@advance_requests@bulk_attach_file.yaml
Labels: size/L

#659 feat: FYLE-86cyxp6pn-employee-settings-admin-changes
  reference/admin.yaml
  reference/approver.yaml
  reference/spender.yaml
  src/admin/openapi.yaml
  src/admin/paths/admin@employee@settings.yaml
  src/approver/openapi.yaml
  src/approver/paths/approver@employee@settings.yaml
  src/components/schemas/employee_settings.yaml
  src/spender/paths/spender@employee@settings.yaml
Labels: size/XL

#666 fix: minor typo fix in secrets scan
  .github/workflows/secrets-scan.yml
Labels: size/XS

#664 feat: Added api docs for advance request pullback api
  reference/spender.yaml
  src/components/schemas/advance_request.yaml
  src/spender/openapi.yaml
  src/spender/paths/spender@advance_requests@pull_back.yaml
Labels: size/M

#667 feat: Added api docs for advance request comments API
  reference/admin.yaml
  reference/approver.yaml
  reference/spender.yaml
  src/admin/openapi.yaml
  src/admin/paths/admin@advance_requests@comments.yaml
  src/approver/openapi.yaml
  src/approver/paths/approver@advance_requests@comments.yaml
  src/components/schemas/advance_request.yaml
  src/spender/openapi.yaml
  src/spender/paths/spender@advance_requests@comments.yaml
Labels: size/L

#668 feat: Added api docs for advance request delete api
  reference/spender.yaml
  src/components/schemas/advance_request.yaml
  src/spender/openapi.yaml
  src/spender/paths/spender@advance_requests@delete.yaml
Labels: size/M

#670 feat: added api docs for adv req remove approver
  reference/admin.yaml
  src/admin/openapi.yaml
  src/admin/paths/admin@advance_requests@remove_approver.yaml
  src/components/schemas/advance_request.yaml
Labels: size/M

#662 feat: Update API contracts for new critical policy violation flow
  reference/admin.yaml
  reference/approver.yaml
  reference/spender.yaml
  src/components/parameters/state.yaml
  src/components/schemas/expense.yaml
  src/components/schemas/fields.yaml
Labels: size/M

#675 fix: FYLE-86cz8jbaw-locale-fix
  reference/spender.yaml
  src/components/schemas/employee_settings.yaml
Labels: size/S

#673 feat: Docs for advance request inquire api
  reference/admin.yaml
  reference/approver.yaml
  src/admin/openapi.yaml
  src/admin/paths/admin@advance_requests@inquire.yaml
  src/approver/openapi.yaml
  src/approver/paths/approver@advance_requests@inquire.yaml
  src/components/schemas/advance_request.yaml
Labels: size/L
